### ISSUE TITLE
Missing `voucherifysdk.umd.production.min.js` after upgrading to 2.9.3

### ISSUE THREAD

**Issue by alex-all3dp** [voucherifyio/voucherify-js-sdk#297]
After upgrading `@voucherify/sdk` to 2.9.3 from 2.9.2 I receive
`Error: Cannot find module '.../node_modules/@voucherify/sdk/dist/voucherifysdk.umd.production.min.js'` when running my unit tests with mocha. 

My app uses ESM and loads the SDK via `import voucherifySdk from '@voucherify/sdk'`

Any idea what could have broken my setup with the latest patch release?
